# Generated by Django 3.2.8 on 2021-10-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211030_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
