# Generated by Django 3.2.8 on 2021-10-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('dimensions', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('body_material', models.CharField(blank=True, max_length=200, null=True)),
                ('body_protection', models.CharField(blank=True, max_length=200, null=True)),
                ('simCard_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('box_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalMemory',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Internal_memory_amount', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryInfo',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('internal_memory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.internalmemory')),
            ],
        ),
        migrations.CreateModel(
            name='MenuLanguages',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalSystem',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RamAmount',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ram_amount', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProccessorAndOs',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('os_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.operationalsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('common_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.commoninfo')),
                ('memory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.memoryinfo')),
                ('proccessor_and_os_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.proccessorandos')),
            ],
        ),
        migrations.AddField(
            model_name='memoryinfo',
            name='ram_amount_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ramamount'),
        ),
        migrations.AddField(
            model_name='commoninfo',
            name='menu_language_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.menulanguages'),
        ),
    ]
