# Generated by Django 3.2.8 on 2021-10-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_menulanguages_menulanguage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonInfo',
            new_name='GeneralInfo',
        ),
        migrations.RenameField(
            model_name='generalinfo',
            old_name='menu_language_id',
            new_name='menu_language',
        ),
        migrations.RenameField(
            model_name='internalmemory',
            old_name='Internal_memory_amount',
            new_name='internal_memory_amount',
        ),
        migrations.RenameField(
            model_name='memoryinfo',
            old_name='internal_memory_id',
            new_name='internal_memory',
        ),
        migrations.RenameField(
            model_name='memoryinfo',
            old_name='ram_amount_id',
            new_name='ram_amount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
    ]
