# Generated by Django 3.2.8 on 2021-10-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211030_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='box_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
