# Generated by Django 3.2.8 on 2021-11-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20211030_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='common_id',
            new_name='general_id',
        ),
    ]
