# Generated by Django 3.2.8 on 2021-11-01 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_common_id_parameters_general_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='internalmemory',
            options={'verbose_name_plural': 'InternalMemories'},
        ),
        migrations.AlterModelOptions(
            name='proccessorandos',
            options={'verbose_name_plural': 'Processors and Os'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Catagories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='parameters_id',
        ),
        migrations.AddField(
            model_name='product',
            name='general_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.generalinfo'),
        ),
        migrations.AddField(
            model_name='product',
            name='memory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.memoryinfo'),
        ),
        migrations.AddField(
            model_name='product',
            name='proccessor_and_os_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.proccessorandos'),
        ),
        migrations.DeleteModel(
            name='Parameters',
        ),
    ]
