# Generated by Django 3.2.8 on 2021-11-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20211101_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='general_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='memory_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='proccessor_and_os_id',
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('general_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.generalinfo')),
                ('memory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.memoryinfo')),
                ('proccessor_and_os_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.proccessorandos')),
            ],
            options={
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='parameters_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.parameters'),
        ),
    ]
