# Generated by Django 3.2.8 on 2021-11-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='menu_language',
        ),
        migrations.RemoveField(
            model_name='memoryinfo',
            name='internal_memory',
        ),
        migrations.RemoveField(
            model_name='memoryinfo',
            name='ram_amount',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='general_id',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='memory_id',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='proccessor_and_os_id',
        ),
        migrations.RemoveField(
            model_name='proccessorandos',
            name='cpu_id',
        ),
        migrations.RemoveField(
            model_name='proccessorandos',
            name='gpu_id',
        ),
        migrations.RemoveField(
            model_name='proccessorandos',
            name='os_id',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parameters_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Cpu',
        ),
        migrations.DeleteModel(
            name='GeneralInfo',
        ),
        migrations.DeleteModel(
            name='Gpu',
        ),
        migrations.DeleteModel(
            name='InternalMemory',
        ),
        migrations.DeleteModel(
            name='MemoryInfo',
        ),
        migrations.DeleteModel(
            name='MenuLanguage',
        ),
        migrations.DeleteModel(
            name='OperationalSystem',
        ),
        migrations.DeleteModel(
            name='Parameters',
        ),
        migrations.DeleteModel(
            name='ProccessorAndOs',
        ),
        migrations.DeleteModel(
            name='RamAmount',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
