const products = [
    {
        '_id': 1,
        'name': 'Redmi Note 10 Pro 6/128GB Grey',
        'image': 'https://mi-home.lt/7726-home_default/mobilusis-telefonas-xiaomi-redmi-note-10-pro-6128gb-grey.jpg',
        'description': 'Xiaomi flagship phone',
        'brand': 'Xiaomi',
        'category': 'Electronics/Smartphones',
        'price': 299.99,
        'countInStock': 50,
        'isPromoted': true,
    },
    {
        '_id': 2,
        'name': 'Apple Airpods - Wireless Bluetooth Headphones',
        'image': 'https://cdn.tele2.lt/media/catalog/product/cache/0/image/x240/17f82f742ffe127f42dca9de82fb58b1/a/p/apple_airpods_su_prastu_krovimo_deklu.png',
        'description': 'Apple airpods',
        'brand': 'Apple',
        'category': 'Electronics/Headphones',
        'price': 149.99,
        'countInStock': 50,
        'isPromoted': false,
    },
    {
        '_id': 3,
        'name': 'Samsung Galaxy Buds Live - Wireless Bluetooth Headphones',
        'image': 'https://cdn.tele2.lt/media/catalog/product/cache/0/image/x240/17f82f742ffe127f42dca9de82fb58b1/s/a/samsung_galaxy_buds_live_white_tele2_3.png',
        'description': 'Samsung Galaxy Buds',
        'brand': 'Samsung',
        'category': 'Electronics/Headphones',
        'price': 149.99,
        'countInStock': 0,
        'isPromoted': false,
    },
    {
        '_id': 4,
        'name': 'Apple iPhone 13 Pro Max (1TB)',
        'image': 'https://cdn.tele2.lt/media/catalog/product/cache/0/image/x300/17f82f742ffe127f42dca9de82fb58b1/i/p/iphone_13_pro_silver_pdp_image_position-1b__wwen_7.png',
        'description': 'Newest iPhone',
        'brand': 'Apple',
        'category': 'Electronics/Smartphones',
        'price': 1859.00,
        'countInStock': 20,
        'isPromoted': true,
    },
    {
        '_id': 5,
        'name': 'Smartwatch Huawei GT 2 Pro (46mm)',
        'image': 'https://cdn.tele2.lt/media/catalog/product/cache/0/image/x240/17f82f742ffe127f42dca9de82fb58b1/h/u/huawei_watch_gt_2_pro_tele2_1.png',
        'description': 'Huawei smartwatch',
        'brand': 'Huawei',
        'category': 'Electronics/Smartwatches',
        'price': 229.00,
        'countInStock': 70,
        'isPromoted': true,
    },
]
export default products